export const stockData = [
  {
    catagory: "Ella food",
    cost: "60",
    credit: true,
    date: "2022-07-14",
    debit: false,
  },
  {
    catagory: "Gas",
    cost: "60",
    credit: false,
    date: "2022-07-11",
    debit: false,
    description: "Gas for car.",
  },
  {
    catagory: "Rent",
    cost: "800",
    credit: false,
    date: "2022-08-01",
    debit: false,
    description: "Payment for rent of house.",
  },
  {
    catagory: "Job Salary",
    cost: "1200",
    credit: false,
    date: "2022-07-15",
    debit: false,
    description: "Salary from working.",
  },
  {
    catagory: "Dinner",
    cost: "95",
    credit: true,
    date: "2022-07-05",
    debit: true,
    description: "Cost of going to dinner with family for a birthday.",
  },
  {
    catagory: "Plane ticket",
    cost: "240",
    credit: false,
    date: "2022-07-28",
    debit: false,
    description: "Cost of flight to Vegas for vacation.",
  },
  {
    catagory: "Shoes",
    cost: "40.99",
    credit: false,
    date: "2022-07-18",
    debit: false,
    description: "New pair of shoes for soccer.",
  },
  {
    catagory: "Grocery",
    cost: "115.99",
    credit: false,
    date: "2022-07-23",
    debit: false,
    description: "Food for the week.",
  },
  {
    catagory: "PayPal",
    cost: "243",
    credit: true,
    date: "2022-06-27",
    debit: true,
    description: "Getting paid from friends for ubers.",
  },
];
